name: Deploy to DigitalOcean (Multi-Branch)

on:
  push:
    branches:
      - main
      - 'feature-*'
      - 'apple'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
            echo "Deploying branch: $BRANCH"

            # Change to project directory
            cd /var/www/task-management

            # Check if branch directory exists, if not, create it
            if [ ! -d "$BRANCH" ]; then
                mkdir -p "$BRANCH"
            fi

            cd "$BRANCH"

            # Clone or pull the latest code
            if [ -d ".git" ]; then
                git pull origin $BRANCH
            else
                git clone -b $BRANCH https://github.com/mstfsrts/task-management.git .
            fi

            npm install

            # Restart or start PM2 process
            pm2 restart taskmanager-$BRANCH || pm2 start server.js --name taskmanager-$BRANCH

            # Create an Nginx configuration file for the subdomain
            CONFIG_FILE="/etc/nginx/sites-available/$BRANCH.taskmanager.mustafasaritas.me"
            if [ ! -f "$CONFIG_FILE" ]; then
                echo "
                server {
                    listen 80;
                    server_name $BRANCH.taskmanager.mustafasaritas.me;

                    location / {
                        proxy_pass http://localhost:3001;
                        proxy_set_header Host \$host;
                        proxy_set_header X-Real-IP \$remote_addr;
                        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    }
                }" > $CONFIG_FILE
                ln -s $CONFIG_FILE /etc/nginx/sites-enabled/
                systemctl restart nginx
            fi
